# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0008_auto_20170109_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part4',
            name='str_401',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_402',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_403',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_404',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_405',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_406',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_407',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_408',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_409',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_410',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_411',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_412',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_413',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_414',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_415',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='str_416',
        ),
        migrations.AddField(
            model_name='part4',
            name='kod_str4',
            field=models.IntegerField(default=1, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb4 \xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part4',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part4',
            name='value_str',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
